### ISSUE TITLE
Handle possibility of failed RAV Request

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol#107]
There are a few repercussions that need to be handled on a failed RAV request.

 - need a way for the RAV failure to be signaled, since it is currently completely handled by the user. This could either be changing the code so the RAV request is handled in library, perhaps by adding another adapter. Alternatively it could be handled by just added a cancel RAV request function.
 - need a way to roll back the min timestamp so the next RAV request includes the receipts from the failed rav request
 - low priority: might need to recheck failed receipts that failed because their timestamp was too low as the may now fall within a valid window (assuming the time is being buffered enough this shouldn't happen)

Might be more things that need to be handled that were not captured here.

Alternatively we can assume that if attempted rav request fails the user may just cut ties with that gateway?

**Comment by aasseman** [comment]
Why not just move
https://github.com/semiotic-ai/timeline-aggregation-protocol/blob/77abbd82d5e0c75cd04b1bce55360a312f036bac/tap_core/src/tap_manager/manager.rs#L160-L161
from `create_rav_request` to `verify_and_store_rav`?
