### ISSUE TITLE
Add description to README explaining how to use the library

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol#17]
In this review I have focused only on documentation - please improve it, plus add some description to README explaining how one can install and then use the library.

_Originally posted by @tkornuta-semiotic in https://github.com/semiotic-ai/timeline_aggregation_protocol/pull/3#pullrequestreview-1320802421_

**Comment by tkornuta-semiotic** [comment]
Let's just "port" the content from GIP once it will be ready/approved

**Comment by aasseman** [comment]
Fixed in #217
