### ISSUE TITLE
Properly handle Signers vs. Senders

### ISSUE THREAD

**Issue by aasseman** [semiotic-ai/timeline-aggregation-protocol#202]
Senders:

* Control their Escrow account
* Add and remove signing addresses to their escrow account

Signers:

* Sign Receipts and RAVs
* There can be multiple signers per Sender/Escrow account
* Signers can be revoked (\~1 month thawing)

tl;dr (pseudo code or something):

```
Sender {
  escrow_account: EscrowAccount
  signers: [Address]
}
```

**Comment by gusinacio** [comment]
Add to linear
