### ISSUE TITLE
Check Receipt State in RAV aggregate receipts

### ISSUE THREAD

**Issue by ColePBryan** [semiotic-ai/timeline-aggregation-protocol#29]
Creating issue to tie to TODO comment.

In RAV aggregate receipts the state of any RAV that is aggregated should be OK, otherwise error should be thrown. This is waiting on #28 to be completed.

**Comment by aasseman** [comment]
@ColePBryan isn't this one fixed?

**Comment by ColePBryan** [comment]
No, this refers to this line: https://github.com/semiotic-ai/timeline-aggregation-protocol/blob/009c829bd2790ea3e8bfc289d807abe6cf1f66d4/tap_core/src/receipt_aggregate_voucher.rs#L52

We just need to add a check that the state of the receipt is correct. I'm not sure if that would work as expected now. The idea was to have the aggregator use the manager and do all required checks then when we are aggregating we just check the receipt state to ensure they are all checked. I think right now we don't have the aggregator using the manager. So unless that is going to change we can just remove this and the TODO comment as well.

**Comment by aasseman** [comment]
I looked at the code again, I still think that we're better off not using the manager in the aggregator for now. The current checks code in the Aggregator is quite straightforward, and besides tap_core does not provide these implementations anyway, and the manager does not really fit for usage outside the indexer in my opinion.
