### ISSUE TITLE
Make sure that the JSON-RPC API can be protected by a WAF

### ISSUE THREAD

**Issue by aasseman** [semiotic-ai/timeline-aggregation-protocol#81]

**Comment by ColePBryan** [comment]
@aasseman what is the status of this issue?

**Comment by aasseman** [comment]
The best we can do is write guidelines for gateway operators in the documentation. Unless we assume that the (non-exhaustive) recommendations above should be obvious.

**Comment by ColePBryan** [comment]
Do you think it's in the expected scope of the documentation? Or is it something someone running the aggregator would be expected to know?
