### ISSUE TITLE
Document public traits exhaustively (in code)

### ISSUE THREAD

**Issue by aasseman** [semiotic-ai/timeline-aggregation-protocol#91]
In particular the adapter traits.
Could have security implications: an erroneous trait implementation could reduce the security and correctness of TAP.

**Comment by tkornuta-semiotic** [comment]
yeah, traits are really lacking documentation, e.g.:

https://docs.rs/tap_core/0.1.0/tap_core/adapters/collateral_adapter/trait.CollateralAdapter.html

We will need to fix this before Ozgur&Ford will start the integration.
